-- Migration: Add embeddings support to x_profiles table
-- This enables RAG/semantic search functionality using Google Gemini embeddings

-- Enable pgvector extension (if not already enabled)
CREATE EXTENSION IF NOT EXISTS vector;

-- Add embedding column to x_profiles table
-- Using 768 dimensions for Google Gemini text-embedding-004
ALTER TABLE x_profiles 
ADD COLUMN IF NOT EXISTS embedding vector(768);

-- Create index for faster vector similarity search
CREATE INDEX IF NOT EXISTS x_profiles_embedding_idx 
ON x_profiles USING ivfflat (embedding vector_cosine_ops)
WITH (lists = 100);

-- Drop existing function if it exists (may have different signature from OpenAI setup)
DROP FUNCTION IF EXISTS search_profiles(vector, double precision, integer);
DROP FUNCTION IF EXISTS search_profiles(vector(1536), float, int);

-- Create function to search profiles by vector similarity
CREATE OR REPLACE FUNCTION search_profiles(
  query_embedding vector(768),
  match_threshold float DEFAULT 0.7,
  match_count int DEFAULT 20
)
RETURNS TABLE (
  x_user_id text,
  username text,
  name text,
  bio text,
  profile_image_url text,
  followers_count bigint,
  following_count bigint,
  similarity float
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT
    p.x_user_id::text,
    p.username::text,
    p.name::text,
    p.bio::text,
    p.profile_image_url::text,
    p.followers_count,
    p.following_count,
    1 - (p.embedding <=> query_embedding) as similarity
  FROM x_profiles p
  WHERE p.embedding IS NOT NULL
    AND 1 - (p.embedding <=> query_embedding) > match_threshold
  ORDER BY p.embedding <=> query_embedding
  LIMIT match_count;
END;
$$;

-- Drop existing function if it exists
DROP FUNCTION IF EXISTS get_profiles_needing_embeddings(int);

-- Create a function to get profiles that need embedding generation
CREATE OR REPLACE FUNCTION get_profiles_needing_embeddings(batch_size int DEFAULT 100)
RETURNS TABLE (
  x_user_id text,
  username text,
  name text,
  bio text
)
LANGUAGE sql
AS $$
  SELECT x_user_id::text, username::text, name::text, bio::text
  FROM x_profiles
  WHERE embedding IS NULL
  LIMIT batch_size;
$$;

-- Add comments for documentation
COMMENT ON COLUMN x_profiles.embedding IS 'Vector embedding (768 dims) generated by Google Gemini text-embedding-004 for semantic search';
COMMENT ON FUNCTION search_profiles IS 'Search profiles using vector similarity (cosine distance) against query embedding';
COMMENT ON FUNCTION get_profiles_needing_embeddings IS 'Get profiles that need embeddings generated in batches';

