import { inngest } from "./client";
import { createClient } from "@supabase/supabase-js";

// NOTE: RAG/Embedding generation now happens in Python backend
// This file only handles basic scraping if needed

// Background job: Scrape user's network
export const scrapeNetwork = inngest.createFunction(
  { 
    id: "scrape-network",
    name: "Scrape X Network"
  },
  { event: "scrape/network.requested" },
  async ({ event, step }) => {
    const { userId, username, accessToken } = event.data;

    // Step 1: Fetch following from X API
    const following = await step.run("fetch-following", async () => {
      try {
        const response = await fetch(
          `https://api.twitter.com/2/users/${userId}/following?max_results=1000&user.fields=description,public_metrics,profile_image_url`,
          {
            headers: {
              Authorization: `Bearer ${accessToken}`,
            },
          }
        );

        if (!response.ok) {
          throw new Error(`Twitter API error: ${response.statusText}`);
        }

        const data = await response.json();
        return data.data || [];
      } catch (error) {
        console.error("Error fetching following:", error);
        return [];
      }
    });

    // Step 2: Save to Supabase
    await step.run("save-to-supabase", async () => {
      const supabase = createClient(
        process.env.NEXT_PUBLIC_SUPABASE_URL!,
        process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
      );
      
      const profiles = following.map((user: any) => ({
        x_user_id: user.id,
        username: user.username,
        name: user.name,
        bio: user.description || "",
        profile_image_url: user.profile_image_url || "",
        verified: false,
        followers_count: user.public_metrics?.followers_count || 0,
        following_count: user.public_metrics?.following_count || 0,
        tweet_count: user.public_metrics?.tweet_count || 0,
        listed_count: user.public_metrics?.listed_count || 0,
        is_protected: user.protected || false,
        last_updated_at: new Date().toISOString(),
      }));
      
      // Upsert profiles
      const { error: profileError } = await supabase
        .from('x_profiles')
        .upsert(profiles, { onConflict: 'x_user_id' });
      
      if (profileError) {
        console.error("Error saving profiles:", profileError);
      }
      
      // Create connection record for the user with their following list
      const followingIds = following.map((user: any) => user.id);
      
      const { error: connectionError } = await supabase
        .from('x_connections')
        .upsert({
          x_user_id: userId,
          mutual_ids: followingIds,
          discovered_at: new Date().toISOString(),
        }, { onConflict: 'x_user_id' });
      
      if (connectionError) {
        console.error("Error saving connections:", connectionError);
      }
      
      return { count: following.length };
    });

    return { 
      success: true, 
      profilesScraped: following.length,
      username,
      message: "Profiles saved. RAG embeddings will be generated by Python backend."
    };
  }
);
